version: "3.9"

services:
  django:
    build:
      context: ./portfolio
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - ./portfolio:/app/
  db:
    image: postgres:13
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - ./volumes/postgres/data/:/var/lib/postgresql/data

